### ISSUE TITLE
Managing Dictionaries no longer possible after deleting all available dictionaries

### ISSUE THREAD

**Issue by bdorer** [ruifontes/Dictionaries#6]
STR:
1. Press CTRL+Shift+F6 to open dictionaries dialogue
2. Activate Manage dictionaries...
3. Delete all available dictionaries.
4. Press OK two times
5. Press again Control+Shift+F6 and activate Manage dictionaries... dialogue:

Current behavior:
No dialogue opens and following error is logged:
ERROR - unhandled exception (14:54:58.991) - MainThread (11216):
Traceback (most recent call last):
  File "C:\Users\Bernd\AppData\Roaming\nvda\addons\dictionaries\globalPlugins\dictionaries\__init__.py", line 397, in manageDicts
    dialog2 = ManageDicts(gui.mainFrame)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bernd\AppData\Roaming\nvda\addons\dictionaries\globalPlugins\dictionaries\__init__.py", line 763, in __init__
    self.list_box_1.SetSelection(0)
wx._core.wxAssertionError: C++ assertion ""N == (-1) || IsValid(N)"" failed at ..\..\src\msw\listbox.cpp(342) in wxListBox::DoSetSelection(): invalid index in wxListBox::SetSelection
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (14:54:59.079) - MainThread (11216):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))

Expected behavior:
The dialogue should open normally so I'm able to install dictionaries..

**Comment by ruifontes** [comment]
Fixed on 2025.08.11
